# Generated by Django 2.1.1 on 2018-10-03 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('cond_Name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.CharField(max_length=75)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=75)),
                ('hourly_wage', models.FloatField()),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_code', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('pur_price', models.FloatField()),
                ('ask_price', models.FloatField()),
                ('time_added', models.DateTimeField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Employee')),
                ('condition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Open_Product_Code',
            fields=[
                ('product_code', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('type_ID', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=75)),
                ('weight', models.FloatField()),
                ('brand', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('invoice_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('past_product_code', models.CharField(max_length=15)),
                ('selling_site', models.URLField()),
                ('vendor', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=30)),
                ('pur_price', models.FloatField()),
                ('sel_price', models.FloatField()),
                ('product_type', models.CharField(max_length=150)),
                ('added_by', models.IntegerField()),
                ('time_added', models.DateTimeField()),
                ('shipment_number', models.CharField(max_length=100)),
                ('time_archived', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Site',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('domain', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('hourly_wage', models.FloatField()),
                ('emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('tracking_number', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('shipment_cost', models.FloatField()),
                ('materials_used', models.TextField()),
                ('material_cost', models.FloatField()),
                ('time_shipped', models.DateTimeField()),
                ('user_shipped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slot_size',
            fields=[
                ('size_title', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('size_volume', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('comp_Name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='open_product_code',
            name='slot_Size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Slot_size'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Product_Type'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='selling_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Sale_Site'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Vendor'),
        ),
    ]
