# Generated by Django 2.1.2 on 2018-10-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
