# Generated by Django 2.1 on 2018-10-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181020_1913'),
        ('backend', '0002_auto_20181022_0502'),
    ]

    operations = [
    ]
