# Generated by Django 2.1.2 on 2018-11-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_merge_20181022_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permissions',
        ),
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'employee'), (2, 'hr'), (3, 'supervisor'), (4, 'admin')], default=1),
        ),
    ]
