# Generated by Django 2.1.1 on 2018-12-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181111_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='archived_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
